pypi published failed on version mismatch

diff --git a/.github/workflows/pypi_release.yml b/.github/workflows/pypi_release.yml
--- a/.github/workflows/pypi_release.yml
+++ b/.github/workflows/pypi_release.yml
@@ -24,9 +24,16 @@ jobs:
         VERSION=$(echo $TAG | sed 's/v//')
         echo "Updating version to $VERSION"
         PROJECT_FILE_PATH=pyproject.toml
-        awk -v new_version="$VERSION" '/^version = "/ {gsub(/"[^"]+"/, "\"" new_version "\"")} 1' "$PROJECT_FILE_PATH" > tmpfile && mv tmpfile "$PROJECT_FILE_PATH"
-        pip install build
-        python -m build --wheel
+        VERSION_FILE=$(grep -m 1 "version =" $PROJECT_FILE_PATH | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3) 
+        if [ $VERSION_FILE = $VERSION ]; then
+            awk -v new_version="$VERSION" '/^version = "/ {gsub(/"[^"]+"/, "\"" new_version "\"")} 1' "$PROJECT_FILE_PATH" > tmpfile && mv tmpfile "$PROJECT_FILE_PATH"
+            pip install build
+            python -m build --wheel
+        else
+            echo "Build Failed due to package version mismatch with github tag and pypoject.toml"
+            exit 1
+        fi
+        
     - name: Store the distribution packages
       uses: actions/upload-artifact@v4.2.0
       with:
